packages:
  - apps/*

allowBuilds:
  appium: true
  appium-ios-tuntap: true
  cypress: true
  edgedriver: true
  esbuild: true
  geckodriver: true
  protobufjs: true
  sharp: true
onlyBuiltDependencies:
  - appium
  - appium-ios-tuntap
  - cypress
  - edgedriver
  - esbuild
  - geckodriver
  - protobufjs
  - sharp
